### ISSUE TITLE
Modification dossier bdd 

### ISSUE THREAD

**Issue by robinsaillard** [robinsaillard/Barcode#16]
Modifier la valeur de base de DOWNLOAD_DIRECTORY avec un dossier par défaut. 

Idée : 

`string download = Environment.GetEnvironmentVariable("USERPROFILE")+@"\"+"Downloads";`

ou 

[Plus propre ici ](https://webdevdesigner.com/q/getting-downloads-folder-in-c-duplicate-15119/#:~:text=la%20m%C3%A9thode%20WinAPI,SavedGames%2C%0A%20%20%20%20SavedSearches%2C%0A%20%20%20%20Videos%0A%7D)

**Comment by MaxHed** [comment]
A tester avant de close l'issue
