### ISSUE TITLE
Correction sur impression pdf

### ISSUE THREAD

**Issue by robinsaillard** [robinsaillard/Barcode#35]
Remplacer Spire.Pdf  pour corriger le message d'erreur sur étiquette pdf : ***Evaluation Warning : The version can be used only for the evaluation purpose...***

**Comment by MaxHed** [comment]
Modifier par RawPrint, qui communique directement avec l'imprimante indiqué, attend que l'imprimante ai terminée l'impression pour supprimer le fichier du dossier téléchargement.
